---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: src/index.md
  label: Home
- type: heading
  label: Content
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: src
  label: Templates
  create: documents
  match: "*.njk"
  new_doc_ext: njk
  templates:
  - nunchucks-template
- type: heading
  label: Globals
- type: document
  path: src/_data/tokens.json
  label: Theme settings
upload_dir: src/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - ELEVENTY_ENV=development
  preview_output_directory: src/dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start
